GENERAL:
  scenario        : GPS_L1CA_TEST
  max_channels    : 12
  ms_to_process   : 60000
  ms_chunk_size   : 100
  in_file         : ./rfdata/class_ifen_8bit_20e6_if_5000445.88565834.bin
  # in_file         : ./rfdata/GPS_Class_2023_Static_IF_Data_2nd_set.bin
  out_folder      : results
  reference_pos_x : 422596.629
  reference_pos_y : -5362864.287
  reference_pos_z : 3415493.797

RFSIGNAL:
  sampling_freq     : 20000000.0
  intermediate_freq : 5000445.88565834
  is_complex        : false
  bit_depth         : 8

CHANNELS:
  signals                 : [gps_l1ca]
  max_active_channels     : [8]

ACQUISITION:
  doppler_range            : 5000.0
  doppler_step             : 100.0
  coherent_integration     : 1
  non_coherent_integration : 5
  threshold                : 12.0

TRACKING:
  min_converg_time_ms   : 100
  correlator_epl_wide   : 0.5
  correlator_epl_narrow : 0.25
  pll_bandwidth_wide    : 15.0
  fll_bandwidth_wide    : 5.0
  dll_bandwidth_wide    : 1.0
  pll_bandwidth         : 10.0
  fll_bandwidth         : 1.0
  dll_bandwidth         : 0.1
  pll_bandwidth_narrow  : 6.0
  fll_bandwidth_narrow  : 0.1
  dll_bandwidth_narrow  : 0.01

MEASUREMENTS:
  frequency   : 1
  pseudorange : true
  doppler     : true
  adr         : true
  cn0         : true